// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	updateSettings: (settings: AppSettings) => __TAURI_INVOKE<AppSettings>("update_settings", { settings }),
	listSessions: () => __TAURI_INVOKE<Session[]>("list_sessions"),
	listRecentSessions: (limit: number) => __TAURI_INVOKE<Session[]>("list_recent_sessions", { limit }),
	createSession: (draft: SessionDraft) => __TAURI_INVOKE<Session>("create_session", { draft }),
	reopenSession: (id: string) => __TAURI_INVOKE<Session>("reopen_session", { id }),
	openSessionNoteState: (id: string) => __TAURI_INVOKE<SessionNoteState>("open_session_note_state", { id }),
	updateSession: (id: string, patch: SessionPatch) => __TAURI_INVOKE<Session>("update_session", { id, patch }),
	deleteSession: (id: string) => __TAURI_INVOKE<null>("delete_session", { id }),
	createEntry: (draft: EntryDraft) => __TAURI_INVOKE<Entry>("create_entry", { draft }),
	listEntries: (sessionId: string) => __TAURI_INVOKE<Entry[]>("list_entries", { sessionId }),
	updateEntry: (id: string, patch: EntryPatch) => __TAURI_INVOKE<Entry>("update_entry", { id, patch }),
	createFinding: (draft: FindingDraft) => __TAURI_INVOKE<Finding>("create_finding", { draft }),
	listFindings: (sessionId: string) => __TAURI_INVOKE<Finding[]>("list_findings", { sessionId }),
	listFindingLibrary: () => __TAURI_INVOKE<FindingLibraryItem[]>("list_finding_library"),
	updateFinding: (id: string, patch: FindingPatch) => __TAURI_INVOKE<Finding>("update_finding", { id, patch }),
	createDraft: (draft: DraftCreate) => __TAURI_INVOKE<Draft>("create_draft", { draft }),
	listDrafts: (sessionId: string) => __TAURI_INVOKE<Draft[]>("list_drafts", { sessionId }),
	listDraftLibrary: () => __TAURI_INVOKE<DraftLibraryItem[]>("list_draft_library"),
	updateDraft: (id: string, patch: DraftPatch) => __TAURI_INVOKE<Draft>("update_draft", { id, patch }),
	deleteDraft: (id: string) => __TAURI_INVOKE<null>("delete_draft", { id }),
	deleteFinding: (id: string) => __TAURI_INVOKE<null>("delete_finding", { id }),
	startAiActionJob: (request: GenerateAiActionRequest, events: Channel<GenerationJobEvent>) => __TAURI_INVOKE<StartAiActionJobResult>("start_ai_action_job", { request, events }),
	getAiActionJobStatus: (jobId: string) => __TAURI_INVOKE<GenerationJobStatus>("get_ai_action_job_status", { jobId }),
	/**
	 *  Enumerate the AI-action jobs still running in the backend.
	 * 
	 *  The webview can reload (or the app can be reopened onto a still-running
	 *  backend) without the worker threads noticing; when that happens the frontend
	 *  has lost its job map and the original invoke `Channel`. On boot it calls this
	 *  to recover the survivors and re-subscribe by polling `get_ai_action_job_status`.
	 */
	listActiveAiActionJobs: () => __TAURI_INVOKE<GenerationJobStatus[]>("list_active_ai_action_jobs"),
	cancelAiActionJob: (jobId: string) => __TAURI_INVOKE<GenerationJobStatus>("cancel_ai_action_job", { jobId }),
	importClipboardScreenshot: (sessionId: string, entryId: string | null, filename: string, dataUrl: string) => __TAURI_INVOKE<Attachment>("import_clipboard_screenshot", { sessionId, entryId, filename, dataUrl }),
	getProviderStatus: () => __TAURI_INVOKE<ProviderStatus>("get_provider_status"),
	refreshProviderStatus: () => __TAURI_INVOKE<ProviderStatus>("refresh_provider_status"),
	getAttachmentPreviewDataUrl: (attachmentId: string) => __TAURI_INVOKE<string | null>("get_attachment_preview_data_url", { attachmentId }),
	readClipboardImageDataUrl: () => __TAURI_INVOKE<string | null>("read_clipboard_image_data_url"),
	copyAttachmentImageToClipboard: (attachmentId: string) => __TAURI_INVOKE<null>("copy_attachment_image_to_clipboard", { attachmentId }),
	copyHtmlToClipboard: (html: string, altText: string) => __TAURI_INVOKE<null>("copy_html_to_clipboard", { html, altText }),
};

/* Constants */
export const EDITOR_HTML_TAGS = ["a","b","br","em","h2","h3","i","img","input","li","ol","p","strong","ul"] as const;

export const MANAGED_ATTACHMENT_PROTOCOL = "qa-scribe-attachment://" as const;

export const PROVIDER_MODEL_DEFAULTS = {"claude_code":null,"codex_cli":null,"copilot_cli":null} as const;

export const PROVIDER_REASONING_DEFAULTS = {"claude_code":null,"codex_cli":null,"copilot_cli":null} as const;

export const SELF_CLOSING_EDITOR_HTML_TAGS = ["br","img","input"] as const;

/* Types */
export type AiProvider = "claude_code" | "codex_cli" | "copilot_cli";

export type AiRun = {
	id: string,
	sessionId: string,
	generationContextId: string | null,
	provider: AiProvider,
	model: string,
	reasoningEffort: string | null,
	promptVersion: string,
	status: AiRunStatus,
	errorMessage: string | null,
	createdAt: string,
	completedAt: string | null,
};

export type AiRunStatus = "running" | "completed" | "failed";

export type AppSettings = {
	schemaVersion: number,
	generationSystemPrompt: string,
	selectedAiProvider?: AiProvider,
	selectedAiModel?: string | null,
	selectedAiModelsByProvider?: Partial<{ [key in AiProvider]: string | null }>,
	selectedAiReasoningEffortsByProvider?: Partial<{ [key in AiProvider]: string | null }>,
	testwareTemplate?: string,
	findingTemplate?: string,
	noteSummaryTemplate?: string,
};

export type Attachment = {
	id: string,
	sessionId: string,
	entryId: string | null,
	filename: string,
	mimeType: string | null,
	sizeBytes: number,
	sha256: string,
	relativePath: string,
	createdAt: string,
};

export type CommandError = {
	kind: CommandErrorKind,
	message: string,
};

export type CommandErrorKind = "validation" | "notFound" | "internal";

export type Draft = {
	id: string,
	sessionId: string,
	aiRunId: string | null,
	kind: DraftKind,
	title: string,
	body: string,
	bodyJson: string | null,
	bodyFormat: string | null,
	metadataJson: string | null,
	createdAt: string,
	updatedAt: string,
};

export type DraftCreate = {
	sessionId: string,
	aiRunId: string | null,
	kind: DraftKind,
	title: string,
	body: string,
	bodyJson?: string | null,
	bodyFormat?: string | null,
	metadataJson?: string | null,
};

export type DraftKind = "session_report" | "testware";

export type DraftLibraryItem = {
	draft: Draft,
	sessionTitle: string,
};

/**
 *  Partial update for a `Draft`. Absent field = no change. `title`/`body` are
 *  non-clearable (`?: string`, no `null`); clearable rich text fields use
 *  `Option<Option<String>>` (`?: string | null`). `body_format` is non-null in
 *  storage, so `null` resets it to the default `html` format.
 */
export type DraftPatch = {
	title?: string,
	body?: string,
	bodyJson?: string | null,
	bodyFormat?: string | null,
	metadataJson?: string | null,
};

export type Entry = {
	id: string,
	sessionId: string,
	entryType: EntryType,
	title: string | null,
	body: string,
	bodyJson: string | null,
	bodyFormat: string | null,
	metadataJson: string | null,
	excludedFromGeneration: boolean,
	createdAt: string,
	updatedAt: string,
};

export type EntryDraft = {
	sessionId: string,
	entryType: EntryType,
	title?: string | null,
	body: string,
	bodyJson?: string | null,
	bodyFormat?: string | null,
	metadataJson?: string | null,
	excludedFromGeneration: boolean,
};

/**
 *  Partial update for an `Entry`. Absent field = no change. `body` and
 *  `excluded_from_generation` are non-clearable (typed `?: string` /
 *  `?: boolean`, no `null`); clearable rich text fields use
 *  `Option<Option<String>>` (`?: string | null`). `body_format` is non-null in
 *  storage, so `null` resets it to the default `html` format.
 */
export type EntryPatch = {
	title?: string | null,
	body?: string,
	bodyJson?: string | null,
	bodyFormat?: string | null,
	metadataJson?: string | null,
	excludedFromGeneration?: boolean,
};

export type EntryType = "note" | "observation" | "api_response" | "log" | "screenshot" | "finding_candidate";

export type Finding = {
	id: string,
	sessionId: string,
	title: string,
	body: string,
	bodyJson: string | null,
	bodyFormat: string | null,
	kind: FindingKind,
	metadataJson: string | null,
	createdAt: string,
	updatedAt: string,
};

export type FindingDraft = {
	sessionId: string,
	title: string,
	body: string,
	bodyJson?: string | null,
	bodyFormat?: string | null,
	kind: FindingKind,
	metadataJson?: string | null,
};

export type FindingKind = "bug" | "question" | "risk" | "follow_up" | "note";

export type FindingLibraryItem = {
	finding: Finding,
	sessionTitle: string,
};

/**
 *  Absent field = no change. `title`/`body` are non-clearable (`?: string`, no
 *  `null`); clearable rich text fields use `Option<Option<String>>`
 *  (`?: string | null`). `body_format` is non-null in storage, so `null` resets
 *  it to the default `html` format.
 */
export type FindingPatch = {
	title?: string,
	body?: string,
	bodyJson?: string | null,
	bodyFormat?: string | null,
	kind?: FindingKind | null,
	metadataJson?: string | null,
};

export type GenerateAiActionKind = "testware" | "finding" | "summary";

export type GenerateAiActionRequest = {
	sessionId: string,
	provider: AiProvider,
	model: string,
	reasoningEffort: string | null,
	action: GenerateAiActionKind,
	noteEntryId?: string | null,
	testwarePreferences?: TestwareGenerationPreferences | null,
};

export type GenerateAiActionResult = {
	generationContext: GenerationContext,
	aiRun: AiRun,
	draft: Draft | null,
	finding: Finding | null,
	noteEntry: Entry | null,
};

export type GenerationContext = {
	id: string,
	sessionId: string,
	createdAt: string,
};

export type GenerationJobEvent = { type: "started"; job_id: string; status: GenerationJobStatus; generation_context: GenerationContext; ai_run: AiRun } | { type: "progress"; job_id: string; status: GenerationJobStatus; message: string } | { type: "partial"; job_id: string; status: GenerationJobStatus; body: string } | { type: "completed"; job_id: string; status: GenerationJobStatus; result: GenerateAiActionResult } | { type: "failed"; job_id: string; status: GenerationJobStatus; error_message: string; ai_run: AiRun | null } | { type: "cancelled"; job_id: string; status: GenerationJobStatus; ai_run: AiRun | null };

export type GenerationJobState = "starting" | "running" | "cancelling" | "completed" | "failed" | "cancelled";

export type GenerationJobStatus = {
	jobId: string,
	sessionId: string,
	action: string,
	state: GenerationJobState,
	progressMessage: string,
	aiRunId: string | null,
	errorMessage: string | null,
	partialText: string | null,
};

export type ProviderCatalogRollout = "disabled" | "diagnostics" | "selector";

export type ProviderCatalogSource = "cliCatalog" | "cliHelp" | "config" | "environment" | "preset";

export type ProviderCatalogState = "idle" | "loading" | "fresh" | "stale" | "unavailable" | "failed";

export type ProviderDefaultOrigin = {
	kind: ProviderDefaultOriginKind,
	label: string,
	displayPath: string | null,
};

export type ProviderDefaultOriginKind = "userConfig" | "projectConfig" | "profile" | "managedConfig" | "runtimeFlag" | "environment" | "cliRecommendation" | "configFile" | "unknown";

export type ProviderDefaultResolution = "configured" | "recommended" | "providerManaged" | "unresolved" | "unavailable";

export type ProviderDefaultSnapshot = {
	state: ProviderDiscoveryState,
	model: ProviderDefaultValue,
	reasoningEffort: ProviderDefaultValue,
	checkedAt: string | null,
	cliVersion: string | null,
	resolutionScope: ProviderResolutionScope,
	error: ProviderDiscoveryError | null,
	warnings: ProviderWarning[],
};

export type ProviderDefaultValue = {
	value: string | null,
	resolution: ProviderDefaultResolution,
	origin: ProviderDefaultOrigin | null,
	recommendedValue: string | null,
};

export type ProviderDescriptor = {
	id: string,
	label: string,
	status: ProviderState,
	available: boolean,
	reason: string,
	command: string | null,
	/**
	 *  Selector projection retained while callers migrate to
	 *  `catalog_snapshot.models`. During diagnostic rollout this deliberately
	 *  remains the compatibility list while the richer catalog is observed.
	 */
	models: ProviderModelDescriptor[],
	catalogSnapshot: ProviderModelCatalogSnapshot,
	defaultSnapshot: ProviderDefaultSnapshot,
	localOnly: boolean,
};

export type ProviderDiscoveryError = {
	code: ProviderDiscoveryErrorCode,
	message: string,
	retryable: boolean,
};

export type ProviderDiscoveryErrorCode = "spawnFailed" | "handshakeFailed" | "timedOut" | "cancelled" | "unsupported" | "protocolIncompatible" | "invalidResponse" | "outputLimit" | "authRequired" | "policyDenied" | "network" | "rateLimited" | "unavailable";

export type ProviderDiscoveryState = "unchecked" | "detected" | "providerManaged" | "stale" | "unresolved" | "unavailable";

export type ProviderEvidenceConfidence = "authoritative" | "observed" | "heuristic" | "static";

export type ProviderModelAvailability = "available" | "policyDisabled" | "unconfigured" | "supportedByBinary" | "staticHint";

export type ProviderModelCapabilities = {
	vision: boolean | null,
	reasoning: boolean | null,
	adaptiveThinking: boolean | null,
	fastMode: boolean | null,
	autoMode: boolean | null,
	contextWindowTokens: number | null,
	maxOutputTokens: number | null,
};

export type ProviderModelCatalogSnapshot = {
	state: ProviderCatalogState,
	source: ProviderCatalogSource,
	models: ProviderModelDescriptor[],
	checkedAt: string | null,
	cliVersion: string | null,
	resolutionScope: ProviderResolutionScope,
	error: ProviderDiscoveryError | null,
	warnings: ProviderWarning[],
};

export type ProviderModelDescriptor = {
	id: string,
	label: string,
	description: string | null,
	source: ProviderModelSource,
	availability: ProviderModelAvailability,
	confidence: ProviderEvidenceConfidence,
	isDefault: boolean,
	reasoningEfforts: string[],
	defaultReasoningEffort: string | null,
	capabilities: ProviderModelCapabilities,
	resolvedModel: string | null,
};

export type ProviderModelSource = "providerDefault" | "environment" | "preset" | "config" | "cliCatalog" | "cliHelp" | "detected";

export type ProviderResolutionScope = {
	kind: ProviderResolutionScopeKind,
	label: string,
};

export type ProviderResolutionScopeKind = "neutral";

export type ProviderState = "ready" | "authRequired" | "installRequired" | "error";

export type ProviderStatus = {
	providers: ProviderDescriptor[],
	catalogRollout: ProviderCatalogRollout,
};

export type ProviderWarning = {
	code: string,
	severity: ProviderWarningSeverity,
	message: string,
};

export type ProviderWarningSeverity = "advisory" | "blocking";

export type Session = {
	id: string,
	title: string,
	sessionContext: string | null,
	objectiveNotes: string | null,
	environment: string | null,
	buildVersion: string | null,
	relatedReference: string | null,
	createdAt: string,
	updatedAt: string,
	lastOpenedAt: string,
};

export type SessionDraft = {
	title: string,
	sessionContext?: string | null,
	objectiveNotes?: string | null,
	environment?: string | null,
	buildVersion?: string | null,
	relatedReference?: string | null,
};

export type SessionNoteState = {
	session: Session,
	noteEntry: Entry,
	testwareDraftCount: number,
	findingCount: number,
};

/**
 *  Partial update for a `Session`. Every field is optional on the wire
 *  (deserialize-only: a missing field naturally deserializes its `Option` as
 *  `None`, so no `#[serde(default)]` is needed → generated `field?:`): an
 *  absent field means "no change".
 * 
 *  Two distinct null contracts, made explicit in the generated TypeScript:
 *  - `title` is required on a Session and cannot be cleared, so it is typed
 *    `title?: string` (`#[specta(type = String)]` drops the `| null`): the
 *    frontend can only set it or omit it, never send `null`. This kills the
 *    prior defect where a `title: null` silently no-oped.
 *  - the `Option<Option<String>>` fields are clearable: absent = no change,
 *    `null` = clear to NULL, a string = set. specta renders them
 *    `field?: string | null`, matching that three-state contract.
 */
export type SessionPatch = {
	title?: string,
	sessionContext?: string | null,
	objectiveNotes?: string | null,
	environment?: string | null,
	buildVersion?: string | null,
	relatedReference?: string | null,
};

export type StartAiActionJobResult = {
	jobId: string,
	status: GenerationJobStatus,
};

export type TestwareDepth = "lean" | "balanced" | "thorough";

export type TestwareGenerationPreferences = {
	technique: TestwareTechnique,
	outputFormat: TestwareOutputFormat,
	depth: TestwareDepth,
	includeNegativeCases: boolean,
	includeBoundaryCases: boolean,
	includeTestData: boolean,
	preserveEvidence: boolean,
	customInstructions: string | null,
};

export type TestwareOutputFormat = "qa_cases" | "checklist" | "gherkin" | "charters" | "coverage_outline";

export type TestwareTechnique = "auto" | "use_case" | "equivalence_boundary" | "decision_table" | "state_transition" | "pairwise" | "risk_based" | "exploratory" | "bdd";

